#!/usr/bin/env bash
#
# install-launcher.sh — put the `ship` command on your PATH.
#
# `ship` opens Claude in your launch vault with --dangerously-skip-permissions,
# auto-runs the launch-conductor skill to reconcile the vault and show the
# board + the single next action, then drops you into an interactive session.
#
# Usage:
#   bash install-launcher.sh [/path/to/vault]
#
# With a vault path, it's saved as the default in
#   ~/.config/launch-conductor/vault
# Without one, the command is still installed; set the default later by
# re-running this with a path, or just run `ship /path/to/vault` once
# (the launcher persists the path it's given).
#
set -euo pipefail

BIN_DIR="${HOME}/.local/bin"
CONFIG_DIR="${HOME}/.config/launch-conductor"
CONFIG_FILE="${CONFIG_DIR}/vault"
CMD="${BIN_DIR}/ship"

mkdir -p "$BIN_DIR" "$CONFIG_DIR"

VAULT_ARG="${1:-}"
if [ -n "$VAULT_ARG" ]; then
  VAULT_ARG="${VAULT_ARG/#\~/$HOME}"
  RESOLVED="$(cd "$VAULT_ARG" 2>/dev/null && pwd)" || {
    echo "error: vault directory not found: $1" >&2
    exit 1
  }
  printf '%s\n' "$RESOLVED" > "$CONFIG_FILE"
  echo "Default vault saved: $RESOLVED"
fi

cat > "$CMD" <<'LAUNCHER'
#!/usr/bin/env bash
#
# ship — open Claude in the launch vault and refresh the launch state.
# Generated by launch-conductor/scripts/install-launcher.sh. Safe to edit.
#
set -euo pipefail

CONFIG_FILE="${HOME}/.config/launch-conductor/vault"

case "${1:-}" in
  -h|--help)
    cat <<'USAGE'
Usage: ship [/path/to/vault]

Opens Claude in the launch vault with --dangerously-skip-permissions, runs the
launch-conductor skill to reconcile the vault and print the board + the single
next action, then hands you an interactive session in that directory.

With no argument, uses the saved default in ~/.config/launch-conductor/vault.
Passing a path uses it and saves it as the new default.
USAGE
    exit 0
    ;;
esac

VAULT="${1:-}"
if [ -n "$VAULT" ]; then
  VAULT="${VAULT/#\~/$HOME}"
  VAULT="$(cd "$VAULT" 2>/dev/null && pwd)" || { echo "ship: vault not found: $1" >&2; exit 1; }
  mkdir -p "$(dirname "$CONFIG_FILE")"
  printf '%s\n' "$VAULT" > "$CONFIG_FILE"
else
  if [ ! -f "$CONFIG_FILE" ]; then
    echo "ship: no vault configured." >&2
    echo "Run once with a path:  ship /path/to/vault" >&2
    exit 1
  fi
  VAULT="$(cat "$CONFIG_FILE")"
  VAULT="${VAULT/#\~/$HOME}"
fi

cd "$VAULT" || { echo "ship: cannot cd into vault: $VAULT" >&2; exit 1; }

exec claude --dangerously-skip-permissions \
  "Use the launch-conductor skill now. The current directory is the launch vault. Reconcile it (run the skill's reconcile script), regenerate Launch Dashboard.md, then show me the terse one-line-per-workstream board and the single next action. Then stop and wait for me."
LAUNCHER

chmod +x "$CMD"
echo "Installed: $CMD"

case ":${PATH}:" in
  *":${BIN_DIR}:"*) ;;
  *)
    echo
    echo "note: ${BIN_DIR} is not on your PATH. Add this to your ~/.zshenv (or shell profile):"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    ;;
esac
